/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Node {
    private Squirrel data;
    private Node left;
    private Node right;

    public Node(Squirrel data) {
        this.data = data;
        this.left = null;
        this.right = null;
    }

    public void setLeft(Node leftNode) {
        this.left = leftNode;
    }

    public void setRight(Node rightNode) {
        this.right = rightNode;
    }

    public Node left() {
        return this.left;
    }

    public Node right() {
        return this.right;
    }

    public Squirrel getData() {
        return this.data;
    }
}

